public class Constants {
    
    public Static final integer DEFAULT_ROWS=5;
    public Static final String SELECT_ONE=label.Select_One;
    public Static final String INVENTORY_LEVEL_LOW = label.Inventory_Level_Low;
    public Static final String DRAFT_ORDER_STATUS='Draft';
    public Static final String ACTIVATED_ORDER_STATUS='Activated';
    public Static final String INVENTORY_ANNOUNCEMENTS='Inventory Announcements';
    public Static final String ERROR_MESSAGE='An error has occurred, please take a screenshot with the URL and send it to IT.';
    public Static final String STANDARD_PRICEBOOK_ID='01s6F00000Fcy7iQAB';
    public Static final list<Schema.PicklistEntry> PRODUCT_FAMILY = Product2.Family.getDescribe().getPicklistValues();
    
}